# Generated by Django 5.1.4 on 2025-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='operating_days',
            field=models.CharField(blank=True, default='Monday, Tuesday, Wednesday, Thursday, Friday', help_text='Comma-separated days (e.g., Monday, Tuesday, Wednesday)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
