# Generated by Django 5.1.4 on 2025-09-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_restaurant_operating_days_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='operating_days',
            field=models.CharField(blank=True, default='Mon, Tue, Wed, Thurs, Fri, Sat, Sun', help_text='Comma-separated days (e.g., Mon, Tue, Wed, Thurs, Fri, Sat, Sun)', max_length=50, null=True),
        ),
    ]
