# Generated by Django 5.1.4 on 2025-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_daily_special',
            field=models.BooleanField(default=False),
        ),
    ]
