# Generated by Django 5.1.4 on 2025-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reservation_table_menucategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount in %'),
        ),
    ]
