# Generated by Django 5.1.4 on 2025-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='comment',
        ),
        migrations.AddField(
            model_name='userreview',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
