# Generated by Django 5.1.4 on 2025-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_userreview_comment_userreview_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, unique=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_daily_special',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
