# Generated by Django 5.1.4 on 2025-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_faq_menuitem_available_menuitem_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount in %'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
