# Generated by Django 5.1.4 on 2025-10-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_table_seats_table_capacity_table_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
