# Generated by Django 5.1.4 on 2025-10-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_menucategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discount_percentage',
        ),
    ]
