# Generated by Django 5.1.4 on 2025-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_menuitem_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.CharField(default='Main Dining Room', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
