# Generated by Django 5.1.4 on 2025-10-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_table_location_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.TextField(blank=True, help_text='List any allergens (e.g., gluten, nuts, dairy)', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.menucategory'),
        ),
    ]
