# Generated by Django 5.1.4 on 2025-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_menuitem_allergens_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
