# Generated by Django 5.1.4 on 2025-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_restaurantinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
