# Generated by Django 5.1.4 on 2025-10-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_cuisine_menuitem_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='description',
        ),
    ]
