# Generated by Django 5.1.4 on 2025-10-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_cuisine_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together=set(),
        ),
    ]
