# Generated by Django 5.1.4 on 2025-10-20 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='operating_days',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
