# Generated by Django 5.1.4 on 2025-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_restaurant_operating_days_menuitem_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='available',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
