# Generated by Django 5.1.4 on 2025-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_ingredient_description_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='name',
            field=models.CharField(default='Default Special', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
