# Generated by Django 5.1.4 on 2025-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_dailyspecial_description_dailyspecial_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Chef', 'Chef'), ('Waiter', 'Waiter'), ('Manager', 'Manager')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
