# Generated by Django 5.1.4 on 2025-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
