# Generated by Django 5.1.4 on 2025-10-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_menuitem_is_vegetarian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
    ]
