# Generated by Django 5.1.4 on 2025-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_allergen_remove_menuitem_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('GLUTEN_FREE', 'Gluten-Free'), ('HALAL', 'Halal'), ('NONE', 'None')], default='NONE', max_length=20, null=True),
        ),
    ]
