# Generated by Django 5.1.4 on 2025-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_order_restaurant_is_active_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='title',
            field=models.CharField(default='Daily Special', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='top_items',
            field=models.BooleanField(default=False),
        ),
    ]
