# Generated by Django 5.1.4 on 2025-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_is_active_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='short_id',
            field=models.CharField(default='ORD001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
