# Generated by Django 5.1.4 on 2025-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('guests', models.IntegerField(default=1)),
            ],
        ),
    ]
